spring:
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1058204421919-2bgs8njve1e9hff9sbuguu1uehdnpc1a.apps.googleusercontent.com
            client-secret: A6BClnmZ0ncMxVIVX_afDT-f
